// ── Placeholder firebase_options.dart ────────────────────────────────────
// This file is auto-generated by `flutterfire configure`.
// Replace this entire file after running:
//   1. npm install -g firebase-tools
//   2. dart pub global activate flutterfire_cli
//   3. flutterfire configure   (inside this project directory)
// ──────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA86bYEuU4dzf3Poep_Qbk6MGld2z-fC8U',
    appId: '1:1071466397976:android:88494cbb9eae4235535e6d',
    messagingSenderId: '1071466397976',
    projectId: 'emadad-a1d92',
    storageBucket: 'emadad-a1d92.firebasestorage.app',
  );

  // ⚠️ REPLACE THESE VALUES with your own from Firebase Console

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosClientId: 'YOUR_IOS_CLIENT_ID',
    iosBundleId: 'com.emadad.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}